QuantumKitHub/PEPSKit.jl

- examples/heisenberg.jl
- examples/test_gauge_fixing.jl
- examples/test_gradients.jl
- src/PEPSKit.jl
- src/algorithms/ctmrg.jl
- src/algorithms/peps_opt.jl
- src/environments/ctmrgenv.jl
- src/states/infinitepeps.jl
- src/utility/eigsolve.jl
- src/utility/rotations.jl
Placeholder PR for an update to the gauge fixing algorithm to one that works for symmetric `TensorMap`s. This implementation fixes the issues #18 , but it breaks the AD since it uses `KrylokvKit.eigsolve` which is not differentiable. Hopefully this works once we add the corresponding rrule.
We should probably also try the [other approaches](https://arxiv.org/abs/2311.11894), but this seemed the simplest one that worked so just adding it here for reference and discussion.
> Update gauge fixing to work with symmetries

- src/algorithms/ctmrg.jl
fixes an issue where we want to print singular values by `diag(S.data)`, which fails for symmetric tensors.
Should probably be handled at TensorKit level by implementing `LinearAlgebra.svdvals` and `LinearAlgebra.eigvals`...
> Fix degenerate singular value check with symmetric tensors

- src/operators/localoperator.jl
Rewrites the local expectation values as a single contraction and switches on the optimal contraction ordering in `@tensor`. This should improve performance, since I'm a bit skeptical the approach of first contracting the full environment and then multiplying in the operator afterward is the most efficient. This currently bypasses the `operator_env` function entirely, although I left it in just in case it is still needed elsewhere.
In particular, this should fix the `OnSite` expectation value, which was wrong before I think (it seems it assumed a transposed environment?). Also, I chose to transpose the `NearestNeighbor` environment density matrix to be consistent with the usual interpretation.
> Rewrite local expectation values as a single contraction

- src/algorithms/contractions/ctmrg_contractions.jl
- src/algorithms/ctmrg/ctmrg.jl
- test/ctmrg/ctmrgschemes.jl
There was an error in the fixedspace truncation which cycled the spaces around, thus leading to errors in the gaugefixing.
This should now be resolved.
Additionally, I removed the gaugefixing procedure from the regular CTMRG calls, as the gaugefixing is repeated in the gradient rules anyways.
I tried to make both schemes of CTMRG use the same indexing convention for the projectors too now, this was an absolute mess so let's try and keep our coordinates the same now :laughing:
> Fix virtual space error for larger unit cells

- src/PEPSKit.jl
- src/algorithms/peps_opt.jl
- src/operators/models.jl
- src/states/infinitepeps.jl
- src/utility/symmetrization.jl
- test/ctmrg/gaugefix.jl
- test/ctmrg/symmetrization.jl
- test/j1j2_model.jl
- test/runtests.jl
- test/tf_ising.jl
This PR cleans up the symmetrization functionality a bit and adds a callback keyword argument for `fixedpoint` which allows to call a user-specified function after each optimization iteration. Also, I added the J1-J2 model Hamiltonian and a small test since I anyway had that code lying around.
> Clean up symmetrization and add optimization callback

- src/operators/localoperator.jl
I defined addition for Localoperators
> Define + for LocalOperators

- src/PEPSKit.jl
- src/algorithms/ctmrg/ctmrg.jl
- src/algorithms/peps_opt.jl
This PR will change and more consistently use the default values in `PEPSKit.Defaults`.
> Change default values

- src/algorithms/ctmrg/ctmrg.jl
This small PR will fix two small things:
1. The `miniter` condition didn't work anymore in `leading_boundary` runs
2. Using the `@set` macro from Accessors.jl for the CTMRG struct wouldn't work due to the type parameter
> Fix CTMRG `miniter` and `Accessors.@set`

- src/PEPSKit.jl
This PR will change the default SVD cotangent problem `rrule_alg` to `Arnoldi`.
After some benchmarking, `Arnoldi` has turned out to be the fastest algorithm in many cases (as compared to `GMRES` and `BiCGStab`). The Krylov dimension has to be chosen according to the chosen environment dimension, so this has to be adapted to the specific problems anyway; but choosing a reasonably large dimension will ensure less warnings and better convergence, usually. To really get rid of the warnings by default (since they turn out to be non-crucial in most cases), I set `verbosity=-1`.
> Improve default SVD `rrule_alg`

- src/PEPSKit.jl
- src/algorithms/contractions/ctmrg_contractions.jl
- src/algorithms/ctmrg/ctmrg.jl
- src/algorithms/ctmrg/sparse_environments.jl
- src/algorithms/peps_opt.jl
- src/utility/svd.jl
- test/ctmrg/fixed_iterscheme.jl
- test/ctmrg/svd_wrapper.jl
- test/heisenberg.jl
In this PR we will use function handles to perform the iterative SVD of the half-infinite environment in CTMRG. To that end, a struct will be implemented that stores all necessary tensors for the environment contraction and on which `tsvd!` can dispatch.
Before doing that, a long-standing issue will be resolved where `IterSVD` would lead to singular vectors which, when supplied to `FixedSVD`, would not lead to element-wise converged environments and thereby making it not possible to use the iterative SVD during PEPS optimization.
> Implement sparse SVD with function handles

- src/PEPSKit.jl
- src/algorithms/ctmrg/ctmrg.jl
- src/algorithms/ctmrg/gaugefix.jl
- src/utility/svd.jl
- test/ctmrg/ctmrgschemes.jl
- test/ctmrg/fixed_iterscheme.jl
- test/ctmrg/gaugefix.jl
- test/ctmrg/gradients.jl
- test/ctmrg/svd_wrapper.jl
- test/heisenberg.jl
- test/j1j2_model.jl
- test/pwave.jl
- test/tf_ising.jl
This PR will change the default SVD algorithm to `TensorKit.SDD` since this generally outperforms `TensorKit.SVD` and is used as the default algorithm in TensorKit (and Base uses `gesdd`). Since this anyways modifies many tests, I will update the tests such that they all use the updated `Defaults` to the fullest possible extent.
> Change default SVD algorithm to `SDD` and update tests

- src/algorithms/ctmrg/ctmrg.jl
This PR removes a line of redundant logging in the `leading_boundary` function.
> Remove CTMRG redundant logging

- src/operators/derivatives.jl
This PR removes references to `RecursiveVec` to fix compatibility with the new KrylovKit.jl
> Excise RecursiveVec

- src/algorithms/peps_opt.jl
- src/environments/ctmrg_environments.jl
Catches the issue with real-valued environments and the `fixed` optimization mode, detected in #100. Thanks to @Yue-Zhengyuan for finding this!
> Warn in case of real environments in `:fixed` mode

- src/PEPSKit.jl
- src/algorithms/contractions/ctmrg_contractions.jl
- src/algorithms/ctmrg/ctmrg.jl
- src/algorithms/ctmrg/projectors.jl
- src/algorithms/ctmrg/simultaneous.jl
- src/algorithms/ctmrg/sparse_environments.jl
- test/ctmrg/gaugefix.jl
- In Corboz's original way ([PRL 113 046402](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.113.046402)) to get projectors from the full-infinite environment, he first performs QR on the two halves and then SVD on the two R tensors. However, it is later refined in [PRB 98 235148](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.98.235148) that there's no need to do QR first, and we can directly do SVD on the two halves. This PR implements the latter method to *replace* the original (instead of adding an option to switch between the two). 
- Before SVD, the indices in the lower half of the two half-infinite environments should be *contracted* instead of *multiplied* (as two linear maps; see original [here](https://github.com/QuantumKitHub/PEPSKit.jl/blob/7d79cb92ba1d3ee6ad9 …
> Fix `FullInfiniteProjector`

- src/algorithms/contractions/ctmrg_contractions.jl
- src/utility/rotations.jl
Small PR which fixes a wrong `conj` and index mismatch in `ctmrg_contractions.jl`. Thanks to @Yue-Zhengyuan and @Sander-De-Meyer for bringing this up!
> Fix faulty CTMRG contractions

- src/algorithms/contractions/vumps_contractions.jl
- src/operators/infinitepepo.jl
- src/operators/transfermatrix.jl
- test/boundarymps/vumps.jl
Refactors the boundary MPS contractions to make use of `@autoopt` and the corresponding index labeling conventions. I also added an actual test for the multi-layer PEPO case, seems this was just not there before for some reason.
> Refactor boundary MPS contractions

- src/PEPSKit.jl
- src/algorithms/optimization/fixed_point_differentiation.jl
This fixes #138 by overwriting the `trscheme` to `FixedSpaceTruncation` in the CTMRG algorithm during differentiation. This is only necessary for `:diffgauge` since for the `:fixed` mode the SVD is anyway fixed and only accepts `NoTruncation`.
> Enforce `FixedSpaceTruncation` during differentiation

- src/algorithms/contractions/bondenv/benv_tools.jl
- src/algorithms/time_evolution/evoltools.jl
- src/algorithms/time_evolution/simpleupdate.jl
This PR refactors the simple update, so that some parts can be reused by full update / neighborhood tensor update in the future.
> Wrap SU intermediate steps into functions

- src/algorithms/time_evolution/evoltools.jl
- src/algorithms/time_evolution/simpleupdate.jl
- src/states/infiniteweightpeps.jl
- test/heisenberg.jl
This PR refactors the function `absorb_weight` and replace the direction labels t, r, b, l (borrowed from YASTN) with the existing constants NORTH = 1, etc. 
In addition, in `_qr_bond` for time evolution, I found that using `leftorth` only appears to be more numerically stable for some reason. So I want to make this change as well. Another possible advantage is that using `leftorth` only can help produce a `bondenv` around `a`, `b` that is a linear map between "un-dualed" spaces, which can save some twists:
```
┌-----------------------┐
|   ┌----┐              |
└---|    |-← a === b →--┘
|benv|   ↓     ↓
┌---|    |-→ a† == b† ←-┐
|   └----┘              |
└-----------------------┘
```
> Refactor `absorb_weight` and use `leftorth` in `_qr_bond`

- src/networks/infinitesquarenetwork.jl
- src/operators/infinitepepo.jl
- src/states/infinitepartitionfunction.jl
- src/states/infinitepeps.jl
The (untested) current implementations of `Base.similar` for our different network types was broken, leading to an `UndefRefError` in the checks on the virtual spaces in the inner constructor because all of the `unitcell` entries are `undef`. I patched it to really map `similar` over the unit cell entries, which I think is more in line with what we want here (e.g. to change the storage type of the entries in `similar(::TensorMap, ...)` style).
For context, I encountered this when calling `similar` on an `InfinitePEPS`, where I really expected the result to have the same virtual space structure. Alternatively, it's not clear that this is the proper way of implementing `Base.similar` and since this was never used or tested, I could also use `Base.copy` and just remove the broken …
> Fix `Base.similar` for physical and contractible network types

- src/algorithms/contractions/ctmrg_contractions.jl
- src/algorithms/contractions/localoperator.jl
- src/algorithms/contractions/vumps_contractions.jl
- src/algorithms/ctmrg/gaugefix.jl
- src/algorithms/toolbox.jl
- src/networks/infinitesquarenetwork.jl
- test/ctmrg/partition_function.jl
- test/ctmrg/pepo.jl
- test/runtests.jl
Implements all the contractions required to run CTMRG for PEPO sandwiches with an arbitrary number of layers.
TODO:
> `CTMRG` support for PEPS-PEPO-PEPS networks

- src/utility/util.jl
Here we loosen the restriction of the number type in `_safe_pow`. This makes sense since `sdiag_pow` should also work on complex diagonal tensor maps. (I need this for a niche application related to differentiating the SVD which has to do with extra phase freedom for complex SVDs.)
> Remove unnecessary type restriction on `_safe_pow`

- src/states/infiniteweightpeps.jl
This PR defines `Base.show` for `SUWeight`, so we can use `display(peps.weights)` to see the diagonal elements in the weight matrices in an `InfiniteWeightPEPS`. It's a simple IO function so I don't have tests for it. A possible future improvement is to define a more compact output for `println` and `print`. 
Example output for `peps` with `U1Irrep` symmetry: 
```
SUWeight{TensorMap{Float64, GradedSpace{U1Irrep, TensorKit.SortedVectorDict{U1Irrep, Int64}}, 1, 1, Vector{Float64}}}
(1, 1, 1):
Irrep[U₁](0) = [1.0, 0.013284183529494106, 0.01025508746347934]
Irrep[U₁](-1) = [0.155297993782553]
(2, 1, 1):
Irrep[U₁](1/2) = [1.0, 0.013284183529494106]
Irrep[U₁](-1/2) = [0.155297993782553]
Irrep[U₁](3/2) = [0.01025508746347934]
(1, 2, 1):
Irrep[U₁](0) = [1.0, 0.013284183529494106]
Irrep[U₁](1) = …
```
> Define `Base.show` for `SUWeight`

- src/algorithms/time_evolution/simpleupdate.jl
This PR addresses issue #169 by adding a iPEPS unit cell size check for simple update. It ensure that the unit cell size should be no smaller than (2, 2), because when updating a nearest neighbor bond, SU generally produces two different tensors connected by this bond.
> Add unit cell size check for simple update

- src/algorithms/optimization/peps_optimization.jl
- src/algorithms/select_algorithm.jl
- src/utility/util.jl
Small fix for wrong relative verbosity in `select_algorithm(fixedpoint, ...)`: we want to have optimizer output for each iteration if the global verbosity is 1.
> Fix optimizer verbosity in `fixedpoint` algorithm selector

- examples/heisenberg_evol/simpleupdate.jl
- src/operators/localoperator.jl
- test/examples/heisenberg.jl
This PR defines `Base.real` and `Base.imag` for a `LocalOperator` to extract its real and imaginary parts, respectively. Relevant test/example code is updated.
> Define `real`, `imag` for `LocalOperator`

- src/states/infiniteweightpeps.jl
Add function to convert an InfinitePEPS to an InfiniteWeightPEPS. This would be useful to have to be able to alternate AD-CTMRG with (trivial) SU for optimization. I'm open to suggestions if someone would want a more general conversion method.
> Add InfinitePEPS to InfiniteWeightPEPS conversion

- examples/boundary_mps.jl
- src/PEPSKit.jl
- src/operators/transfermatrix.jl
- test/boundarymps/vumps.jl
Here I rename the function to `initialize_mps` to make it consistent with our naming conventions and also add an optional function and type arguments such that it has the function signature
```julia
initialize_mps(f=randn, T=scalartype(O), O::Union{InfiniteTransferMatrix,MultilineTransferMatrix}, arg)
```
> Refactor `initializeMPS`

- src/Defaults.jl
- src/PEPSKit.jl
- src/algorithms/ctmrg/projectors.jl
- src/algorithms/optimization/fixed_point_differentiation.jl
- src/utility/svd.jl
- src/utility/util.jl
- test/examples/heisenberg.jl
- test/gradients/ctmrg_gradients.jl
- test/utility/svd_wrapper.jl
In this PR we will add a rrule for `tsvd!` which supports Lorentzian broadening. To that end, I copy over TensorKit's [`svd_pullback!`](https://github.com/Jutho/TensorKit.jl/blob/fa1551472ac74d7f2a61bdb2135cf418c8c53378/ext/TensorKitChainRulesCoreExt/factorizations.jl#L150) and modify the `save_inv` function to support a broadened inverse.
Additionally, I will add a keyword argument to control the gauge-dependency warnings in that reverse-rule (which is currently not possible) since in some optimizations, the gauge-dependency warnings are really out of control even though they are non-problematic.
> Add modified `tsvd!` reverse-rule with Lorentzian broadening

- src/environments/ctmrg_environments.jl
This is a minor change that preserves the scalartype of the network for the `CTMRGEnv` constructor
> Fix environment constructor scalar type

- src/utility/svd.jl
This avoids looping over blocks that will end up being truncated completely, ie that would get `howmany = 0`.
This probably fixes #185, although I don't have an explicit case to check this on.
> Rewrite svd to avoid empty blocks

- src/utility/svd.jl
- test/utility/svd_wrapper.jl
Initiated from #192, this PR updates/fixes the Lorentzian broadening in the SVD reverse-rule. I also updated the corresponding test where we can see that degenerate singular values lead to wrong gradients if there is no broadening and *no cutoff*.
In the tests on random matrices it seems that using a cutoff for the degenerate inverse singular value differences - thereby just setting them to zero - kind of has the same effect as the broadening.
> Update SVD reverse-rule broadening

- src/algorithms/contractions/ctmrg_contractions.jl
Small PR to fix diagrams in the docstrings of `renormalize_east_edge` and `renormalize_west_edge`, as found in #193.
> Fix edge renormalization diagrams

- Project.toml
- src/algorithms/toolbox.jl
- test/ctmrg/correlation_length.jl
- test/runtests.jl
Fix #197 
The current fix also changes the definition of the correlation length: it includes the size of the unit cell inside. I am not sure about this change, I can discard it if it breaks MPSKit conventions.
I still think there is something wrong: in the AKLT case, this fix gives a correlation length around 1 when I believe it is around 2 (as published in https://link.aps.org/doi/10.1103/PhysRevB.96.121115), but I am less sure where the factor 2 is wrong.
I can add the AKLT case as a test, regardless of the factor 2 just to check if it executes.
> Fix row and column mismatch in `correlation_length` with unit cells

- src/algorithms/ctmrg/projectors.jl
This PR replaces `@set` by `@reset` to normalize the truncation error in `compute_projector`, as noted by @Yue-Zhengyuan. Closes #204.
> Properly normalize truncation error in `compute_projector`

- src/operators/localoperator.jl
- src/states/infiniteweightpeps.jl
- test/runtests.jl
- test/utility/iwpeps_rotation.jl
- test/utility/localoperator.jl
This PR defines and tests `TensorKit.sectortype` and `TensorKit.spacetype` for `LocalOperator`, `SUWeights` and `InfiniteWeightPEPS`
The formatter also made some changes in docstrings, I can revert if you prefer reducing the diff.
> spacetype for PEPSKit objects

- src/PEPSKit.jl
- src/environments/ctmrg_environments.jl
- src/operators/infinitepepo.jl
- src/states/infinitepartitionfunction.jl
- src/states/infinitepeps.jl
- src/states/infiniteweightpeps.jl
We implement VectorInterface's scale and add functions for `InfinitePEPS`. Previously, this would spit out warnings since OptimKit had to use fallback functions.
Closes #225. Thanks @Yue-Zhengyuan for taking notice!
> Implement VectorInterface's `scale!!` and `add!` for `InfinitePEPS`

- src/PEPSKit.jl
- src/algorithms/contractions/localoperator.jl
- src/algorithms/toolbox.jl
- src/utility/util.jl
Replace the expectation value calculation for PEPS with computing `tr(H * rho)`. 
I checked the contraction costs and the leading cost is the same for both local operators, local norms and local density matrices. (In fact, the optimal contraction order for a single site local operator is exactly first computing the reduced densitymatrix and then contracting with the operator).
The main difference here is that instead of computing both the operator and the norm network, we can simply compute the density matrix once, divide it by its trace, and then evaluate the operator.
I'll try and include some benchmarks as well later, just to prove that everything is behaving as desired, but overall it seems to be between 25-40% faster to evaluate expectation values like this, and the memory usage …
> Reduced density matrices

- src/algorithms/correlators.jl
- test/runtests.jl
- test/utility/correlator.jl
This PR fixes same-row/column correlator for fermionic PEPS (issue #231). A new test file `test/utility/correlator.jl` is also added.
The problem was caused by some extra twists required by VUMPS, which should not be present for the evaluation of expectation values. In VUMPS, a column transfer matrix is constructed as follows (see e.g. Eq. A31 in SciPost Phys. 18, 012 (2025))
Extra twists are required on the physical legs of the "bra" MPS in the bottom. In `correlator` it is replaced by the south-edge CTM tensor. However, when evaluating expectation values, there should be no twists in the network. 
When calculating the numerator `Vo` (which contains the operator to be measured), the following function is called (the extra virtual leg in the operator MPO contributed one more leg to `GL`): …
> Fix correlator for fermionic PEPS

- src/algorithms/contractions/ctmrg_contractions.jl
- test/ctmrg/unitcell.jl
This PR rewrites `renormalize_north_edge`, `renormalize_east_edge` and `renormalize_south_edge` to have them reuse `renormalize_west_edge`. `renormalize_west_edge` was rewritten in #229 to optimize the permutations. This PR fixes #220, part of #205.
- the formatter made changes in the tensor diagrams. I can undo them if you prefer minimizing the diff
- I added a test for a 4x4 unit cell with each bond different
> [Perf] reuse `renormalize_west_edge` for all directions

- src/operators/localoperator.jl
- test/utility/localoperator.jl
Fixes #259.
Instead of applying a `flip` to the auxiliary space to get rid of the dual (which would also be correct I think), I decided to change the underlying contraction such that it no longer makes implicit assumptions on the auxiliary space.
> Fix `add_physical_charge` for fermionic operators

- src/operators/infinitepepo.jl
- test/utility/suweight_rotation.jl
The old implementation of `rotl90` etc. for InfinitePEPO only rotated the arrangement of each tensor in the PEPO unit cell, but forgot to rotate each tensor themselves (i.e. permute their legs). This PR fixes this issue.
> Fix InfinitePEPO rotation

- src/algorithms/time_evolution/evoltools.jl
- src/algorithms/time_evolution/simpleupdate.jl
- src/algorithms/time_evolution/simpleupdate3site.jl
- src/operators/infinitepepo.jl
- test/examples/j1j2_finiteT.jl
- test/runtests.jl
- test/timeevol/cluster_projectors.jl
- test/timeevol/cluster_tools.jl
This PR adds the 3-site version of simple update for PEPO, which deals with Hamiltonians containing up to next-nearest neighbor terms. The J1-J2 model is used to test the algorithm by comparing the calculated finite-temperature energy (both tr(ρH) and ⟨ρ|H|ρ⟩) with high-temperature expansion results in https://doi.org/10.1103/PhysRevB.67.014416 (as @ogauthe did in #215).
> Simple update for PEPO (3-site version)

- src/algorithms/contractions/ctmrg_contractions.jl
- test/ctmrg/partition_function.jl
This PR is a follow-up to #229 and #237. It replaces `@autoopt` by explicit contraction scheme in CTMRG partition function contractions. I assumed the optimal permutation was the same as for a wavefunction and reproduced the same order.
I do not really understand which constraints are imposed by planar non-braiding categories, so I may be doing illegal permutations. I do not know how to check for these, I am happy to learn.
> [perf] avoid `@autoopt` for partition function

- README.md
- docs/src/index.md
- src/environments/ctmrg_environments.jl
- src/states/infinitepartitionfunction.jl
- src/states/infinitepeps.jl
- test/ctmrg/fixed_iterscheme.jl
- test/ctmrg/flavors.jl
- test/ctmrg/jacobian_real_linear.jl
- test/ctmrg/unitcell.jl
- test/examples/heisenberg.jl
- test/examples/j1j2_model.jl
- test/examples/tf_ising.jl
- test/utility/svd_wrapper.jl
- test/utility/symmetrization.jl
See #265.
I also tried to simplify the constructors a bit in the process by splitting out the filling of the physical and virtual spaces depending on how were provided. I at least removed a bunch of things, not sure if this actually made things simpler.
> Remove support for integer space specifiers in state and environment constructors

- src/algorithms/correlators.jl
- src/operators/localoperator.jl
- test/utility/localoperator.jl
I stumbled upon this bug when I was trying to run SU for Hamiltonians with non-uniform physical spaces. It turns out that the rotation functions for `LocalOperator`s would only work for $1\times1$ unit cells or uniform lattices - this should fix it. (I hope my cold-ridden brain actually did the right thing to fix it but I added some tests so it should be fine, hopefully.) I also renamed the functions for index rotations to remove the type piracy.
> Fix `rotl90`, `rotr90` and `rot180` for `LocalOperator`
